{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubernetes-portal.serviceAccountName" . }}
  labels:
{{ include "kubernetes-portal.labels" . | indent 4 }}
{{- end -}}
